global:
  scrape_interval: 15s  # frecuencia de recolección (ajústala si quieres más granularidad)

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi:8000']