apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501       # puerto interno
      targetPort: 8501
      nodePort: 30081  # puerto externo accesible desde la m√°quina host
  type: NodePort