apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: spartron12/streamlit-app:1.0
          ports:
            - containerPort: 8501
          env:
            - name: API_URL
              value: "http://fastapi-service:8000"